"""Django settings for smartplug_app project, the settings in this file are
shared in both build modes: development and production.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from ..admin_settings import (
    SESSION_TIMEOUT_SECONDS,
    FRONTEND_ORIGINS,
    ALLOWED_HOSTS_LIST,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django_eventstream",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "smartplug_app.apps.SmartplugApp",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "smartplug_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "smartplug_app.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTHENTICATION_BACKENDS = [
    "smartplug_app.authentication_backend.AuthenticationBackend"
]

EVENTSTREAM_CHANNELMANAGER_CLASS = (
    "smartplug_app.channel_manager.ChannelManager"
)
EVENTSTREAM_ALLOW_ORIGINS = FRONTEND_ORIGINS
EVENTSTREAM_ALLOW_CREDENTIALS = True
EVENTSTREAM_ALLOW_HEADERS = "Authorization"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Berlin"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --------------------------

# The time in seconds after which a user is signed out if no activity was
# registered.
SESSION_COOKIE_AGE = SESSION_TIMEOUT_SECONDS

# Transfer cookie only if using HTTPS, not HTTP.
SESSION_COOKIE_SECURE = True

# Make cookie inaccesible from javascript.
SESSION_COOKIE_HTTPONLY = True

# Prevents the cookie from being sent by the browser to the target site in all
# cross-site browsing context, even when following a regular link.
SESSION_COOKIE_SAMESITE = "Strict"

# Whether to expire the session when the user closes their browser.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# --------------------------

# The cookie is only send over HTTPS, not HTTP.
CSRF_COOKIE_SECURE = True

# This flag prevents the cookie from being sent in cross-site requests.
CSRF_COOKIE_SAMESITE = "Strict"

# A list of trusted origins for unsafe requests (e.g. POST).
CSRF_TRUSTED_ORIGINS = FRONTEND_ORIGINS

# --------------------------

# The server allows credentials to be included in cross-origin HTTP requests.
CORS_ALLOW_CREDENTIALS = True

# A list of origins that are authorized to make cross-site HTTP requests.
CORS_ALLOWED_ORIGINS = FRONTEND_ORIGINS

# --------------------------

# A list of strings representing the host/domain names that this Django site
# can serve. This is a security measure to prevent HTTP Host header attacks.
ALLOWED_HOSTS = ALLOWED_HOSTS_LIST

# Disable rendering for REST endpoint dev page.
# Source: https://stackoverflow.com/q/42829782
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    )
}