"""
Django settings for smartplug_app project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from ..admin_settings import (
    SESSION_TIMEOUT_SECONDS,
    FRONTEND_ORIGINS,
    ALLOWED_HOSTS_LIST,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django_eventstream",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "smartplug_app.apps.SmartplugApp",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "smartplug_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "smartplug_app.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTHENTICATION_BACKENDS = [
    "smartplug_app.authentication_backend.AuthenticationBackend"
]

EVENTSTREAM_CHANNELMANAGER_CLASS = (
    "smartplug_app.channel_manager.ChannelManager"
)
EVENTSTREAM_ALLOW_ORIGINS = FRONTEND_ORIGINS
EVENTSTREAM_ALLOW_CREDENTIALS = True
EVENTSTREAM_ALLOW_HEADERS = "Authorization"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# TODO: more comments what those settings do / why they are set like this

# --------------------------

SESSION_COOKIE_AGE = SESSION_TIMEOUT_SECONDS

# transfer cookie only using https
SESSION_COOKIE_SECURE = True

# Make cookie inaccesible to javascript.
SESSION_COOKIE_HTTPONLY = True

SESSION_COOKIE_SAMESITE = "Strict"

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# --------------------------

CSRF_COOKIE_SECURE = True

CSRF_COOKIE_SAMESITE = "Strict"

CSRF_TRUSTED_ORIGINS = FRONTEND_ORIGINS

# --------------------------

CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = FRONTEND_ORIGINS

# --------------------------

ALLOWED_HOSTS = ALLOWED_HOSTS_LIST
