persistence true
persistence_location /var/lib/mosquitto/
# TODO: change 0.0.0.0 to something more strict ???
listener 1883 0.0.0.0
# This code is used for TLS encryption
# listener 8883 0.0.0.0
# cafile /var/lib/mosquitto/ssl/server.crt
# certfile /var/lib/mosquitto/ssl/server.crt
# keyfile /var/lib/mosquitto/ssl/server.key
# require_certificate true
# tls_version tlsv1.2
allow_anonymous false
password_file /etc/mosquitto/passwd
log_type all
log_dest stdout
log_dest file /var/log/mosquitto/mosquitto.log
include_dir /etc/mosquitto/conf.d
