openapi: 3.1.0
info:
  title: Smartplug Dirigent
  description: This API allows to view and control smartplugs.
  version: 0.1.0

components:
  schemas:

    ItemId:
      type: string

    TreeItem: 
      type: object
      properties:
        label:
          type: string
        id:
          $ref: '#/components/schemas/ItemId'
        isOn:
          type: boolean
        isAvailable:
          type: boolean
      required:
        - label
        - id
        - isOn
        - isAvailable
      additionalProperties: false

    TreeItemDevice:
      allOf:
        - $ref: '#/components/schemas/TreeItem'
        - type: object

    ItemList:
      type: array
      items:
        oneOf:
          - $ref: '#/components/schemas/TreeItemGroup'
          - $ref: '#/components/schemas/TreeItemDevice'

    TreeItemGroup:
      allOf:
        - $ref: '#/components/schemas/TreeItem'
        - type: object
          properties:
            children:
              $ref: '#/components/schemas/ItemList'
          required:
            - children
          additionalProperties: false

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
      additionalProperties: false
      example:
        detail: 'ERROR: The request did not match the expected schema. [2025-07-08 13:50:18.131863]'

  responses:

    400BadRequest:
      description: Bad Request, returned e.g. if the schema of the response is invalid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    401Unauthorized:
      description: Unauthorized, the user is not logged in.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    500InternalServerError:
      description: Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

paths:

  /:
    get:
      summary: The endpoint of the frontend (HTML and JavaScript).
      description: The endpoint of the frontend (HTML and JavaScript).
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string
                format: html

  /api/csrf:
    get:
      summary: The endpoint to get a CSRF token from the server.
      description: The endpoint to get a CSRF token from the server. The CSRF token is required to make other request types than GET.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  csrfToken:
                    type: string
                required:
                - csrfToken
                additionalProperties: false
                example:
                  csrfToken: f397hpqw3h87dq2q2rh
        '400':
          $ref: '#/components/responses/400BadRequest'
        '500':
          $ref: '#/components/responses/500InternalServerError'

  /api/login:
    post:
      summary: The endpoint to provice user credentials for login.
      description: The endpoint to provice user credentials for login. If valid credentials are provided the user will be logged in.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  pattern: ^([a-zA-Z0-9_.]{1,40}@mylab\.local)|(MYLAB\\[a-zA-Z0-9]{1,20})$
                  # TODO: switch to correct pattern
                  # pattern: ^([a-zA-Z0-9_.]{1,40}@(anschuetz\.com)|(anschuetz\.uk)|(extern\.anschuetz\.com)|(raykiel\.com))|(NT_RMKIEL\\[a-zA-Z0-9_.]{1,20})$
                password:
                  type: string
                  pattern: ^[a-zA-Z0-9^!$%&()\[\]{}=?+*~#'-_.,;:\|<>"°]{1,100}$
                  # TODO: switch to correct pattern
                  # pattern: ^[a-zA-Z0-9^!$%&()\[\]{}=?+*~#'-_.,;:\|<>"°]{12,100}$
              required:
                - username
                - password
              additionalProperties: false
              example:
                username: max.mustermann@anschuetz.com
                password: U5p2A%8!9hXz$r3#
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string
                format: html
        '400':
          $ref: '#/components/responses/400BadRequest'
        '500':
          $ref: '#/components/responses/500InternalServerError'

  /api/logout:
    post:
      summary: The endpoint to log out from an active session.
      description: The endpoint to log out from an active session.
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string
                format: html
        '400':
          $ref: '#/components/responses/400BadRequest'
        '500':
          $ref: '#/components/responses/500InternalServerError'

  /api/get-tree:
    get:
      summary: The endpoint to get the device tree.
      description: The endpoint to get the device tree. The device tree is a representation of the structure and the current state of the smartplug devices configured in the system.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemList'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '500':
          $ref: '#/components/responses/500InternalServerError'

  /api/switch:
    post:
      summary: The endpoint to turn smartplugs ON or OFF.
      description: The endpoint to turn smartplugs ON or OFF.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  pattern: ^[a-f0-9]{64}$
                  description: The unique id of the item.
                desired_isOn:
                  type: boolean
                  description: Whether the goal is to turn the item ON (true) or OFF (false).
              required:
                - id
                - desired_isOn
              additionalProperties: false
              example:
                id: Smartplug-35197149258152
                desired_isOn: true
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '500':
          $ref: '#/components/responses/500InternalServerError'

  /api/get-active-users:
    get:
      summary: The endpoint a list of the active users.
      description: The endpoint a list of the active users. I.e. the users that are logged in and have an active session.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example: ['Max Mustermann', 'John Doe']
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '500':
          $ref: '#/components/responses/500InternalServerError'

  /api/get-session-expiry-date:
    get:
      summary: The endpoint to get the date when the session of the requesting user expires.
      description: The endpoint to get the date when the session of the requesting user expires. The date also inlcudes the exact time.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_expiry_date:
                    type: string
                required:
                - session_expiry_date
                additionalProperties: false
                example:
                  session_expiry_date: 2011-11-04T00:05:23+04:00
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '500':
          $ref: '#/components/responses/500InternalServerError'